INSERT INTO Vendor (Address1,City,Province,PostalCode,Phone,Type,Name,Email)VALUES ('123 Maple 
St','London','On', 'N1N-1N1','(555)555-5555','Trusted','ABC Supply Co.','abc@supply.com');
INSERT INTO Vendor (Address1,City,Province,PostalCode,Phone,Type,Name,Email) VALUES ('543 
Sycamore Ave','Toronto','On', 'N1P-1N1','(999)555-5555','Trusted','Big Bills 
Depot','bb@depot.com');
INSERT INTO Vendor (Address1,City,Province,PostalCode,Phone,Type,Name,Email) VALUES ('922 Oak 
St','London','On', 'N1N-1N1','(555)555-5599','Untrusted','Shady Sams','ss@underthetable.com');
INSERT INTO Vendor (Address1,City,Province,PostalCode,Phone,Type,Name,Email) VALUES ('1227 Hyper
St','London','On', 'H7P-3R1','(519)555-1227','Untrusted','Brayden Co.','bt@youtube.com');
-- INSERT INTO Vendor (Address1,City,Province,PostalCode,Phone,Type,Name,Email) VALUES ('123 Oak Ave','London','On', 'N1N-1N1','(555)555-5551','Trusted','Case One','c1@here.com');

-- drop table if exists Product;
-- CREATE TABLE Product (
--        id varchar(255) generated by default as identity,
--       costprice numeric(19,2),
--       eoq integer not null,
--       msrp numeric(19,2),
--       name varchar(255),
--       qoh integer not null,
--       qoo integer not null,
--       qrcode varchar(255),
--       qrcodetxt varchar(255),
--       rop integer not null,
--       vendorid integer not null,
--       primary key (id)
--     );

--     '1-P0-test',
--     1, 'test', 50.00,
--     60.00, 10, 40, /* For this, we take the price and then divide it by lets say 500 -> 2,000 for the bigger items */
--     15, 25, '', '',

INSERT INTO Product (id,vendorid, name, costprice,msrp, rop, eoq, qoh, qoo, qrcode,qrcodetxt) VALUES (
  '1-P0-test',1, 'test', 50.00,60.00, 10, 40, 15, 25, '', '');
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '1-P1-test',
    1, 'test1', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '1-P2-test',
    1, 'test2', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );

INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '2-P0-test',
    2, 'test', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '2-P1-test',
    2, 'test1', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '2-P2-test',
    2, 'test2', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );

INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '3-P0-test',
    3, 'test', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '3-P1-test',
    3, 'test1', 50.00,
    60.00, 10, 40,
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '3-P2-test',
    3, 'test2', 50.00,
    60.00, 10, 40, 
    15, 25, '', ''
    );

INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '4-P0-Hbt_18in_36in',
    4, '18in by 36in Habitat', 59.00,
    49.99, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '4-P1-Pet_Hamster',
    4, 'Hamster', 22.49,
    20.00, 10, 40, 
    15, 25, '', ''
    );
INSERT INTO Product (
  id,
  vendorid, name, costprice,
  msrp, rop, eoq, 
  qoh, qoo, qrcode,qrcodetxt
  ) VALUES (
    '4-P2-Food_Hamster',
    4, 'Hamster Food', 13.99,
    12.99, 10, 40,
    15, 25, '', ''
    );


-- INSERT INTO Product (
--   id,
--   vendorid, name, costprice,
--   msrp, rop, eoq, 
--   qoh, qoo, qrcode,qrcodetxt
--   ) VALUES (
--     'C1001',
--     6, 'Super Widget', 109.99,
--     122.99, 10, 8,
--     15, 0, '', ''
--     );

-- INSERT INTO Product (
--   id,
--   vendorid, name, costprice,
--   msrp, rop, eoq, 
--   qoh, qoo, qrcode,qrcodetxt
--   ) VALUES (
--     'C1002',
--     6, 'Super Widget', 19.99,
--     22.99, 10, 10,
--     15, 0, '', ''
--     );
